[package]
name = "dmarc_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.6.0"
clap = { version = "4.5.20", features = ["derive"] }

